name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  BUCKET_NAME: servlet-webapp-deployment-phanvvz7
  BEANSTALK_APP_NAME: servlet-webapp
  BEANSTALK_ENV_NAME: servlet-webapp-env

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      #     aws-region: ${{ env.AWS_REGION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload WAR to S3
        run: |
          aws s3 cp target/*.war s3://${{ env.BUCKET_NAME }}/webapp-${{ github.sha }}.war

      # - name: Deploy to Elastic Beanstalk
      #   run: |
      #     aws elasticbeanstalk create-application-version \
      #       --application-name ${{ env.BEANSTALK_APP_NAME }} \
      #       --version-label ${{ github.sha }} \
      #       --source-bundle S3Bucket=${{ env.BUCKET_NAME }},S3Key=webapp-${{ github.sha }}.war

      #     aws elasticbeanstalk update-environment \
      #       --environment-name ${{ env.BEANSTALK_ENV_NAME }} \
      #       --version-label ${{ github.sha }}
