name: Java Servlet Deployment
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose deployment action'
        required: true
        type: choice
        options:
          - build
          - deploy
          - destroy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'corretto'
      
      - name: Build with Maven
        run: mvn clean package
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      
      - name: Deploy to Elastic Beanstalk
        if: ${{ github.event.inputs.action == 'deploy' }}
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name servlet-web-application \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=your-bucket,S3Key=path/to/your/webapp.war
          
          aws elasticbeanstalk update-environment \
            --environment-name servlet-environment \
            --version-label ${{ github.sha }}
